repos:
    -   repo: https://github.com/antonbabenko/pre-commit-terraform
        rev: v1.81.0
        hooks:
            - id: terraform_fmt
            - id: terraform_validate
        # - id: terraform_tflint
        # - id: terrascan
        # - id: terraform_tfsec

    -   repo: https://github.com/NASA-AMMOS/slim-detect-secrets
        # using commit id for now, will change to tag when official version is released
        rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
        hooks:
          - id: detect-secrets
            args:
              - '--baseline'
              - '.secrets.baseline'
              - --exclude-files '\.secrets..*'
              - --exclude-files '\.git.*'
              - --exclude-files '\.pre-commit-config\.yaml'
              - --exclude-files '.*\.tfstate'
              - --exclude-files '.*\.tfvars'
