repos:
    # Although this is a Python repository, the source code isn't installed
    # into a package (the `setup.cfg` is unmodified from the upstream template
    # repo), and so many of the checks here fail. I'm commenting them out in
    # case this becomes a proper Python package some day so we can turn them
    # back on.

    # -   repo: https://github.com/pre-commit/pre-commit-hooks
    #     rev: v4.4.0
    #     hooks:
    #         -   id: trailing-whitespace
    #             exclude: REQUIREMENTS\.md$
    #         -   id: end-of-file-fixer
    #             exclude: REQUIREMENTS\.md$
    #         -   id: check-executables-have-shebangs
    #         -   id: check-merge-conflict
    #         -   id: debug-statements
    #         -   id: check-yaml
    #             files: .*\.(yaml|yml)$
    #         -   id: check-json
    #         -   id: pretty-format-json

    -   repo: https://github.com/antonbabenko/pre-commit-terraform
        rev: v1.81.0
        hooks:
            - id: terraform_fmt
            - id: terraform_validate
        # - id: terraform_tflint
        # - id: terrascan
        # - id: terraform_tfsec

    # -   repo: https://github.com/asottile/reorder_python_imports
    #     rev: v2.6.0
    #     hooks:
    #         -   id: reorder-python-imports
    #             files: ^src/|tests/

    # -   repo: local
    #     hooks:
    #         -   id: mypy
    #             name: mypy
    #             entry: mypy src
    #             language: system
    #             pass_filenames: false

    # -   repo: local
    #     hooks:
    #         -   id: black
    #             name: black
    #             entry: black
    #             files: ^src/|tests/
    #             language: system
    #             types: [python]

    # -   repo: local
    #     hooks:
    #         -   id: flake8
    #             name: flake8
    #             entry: flake8 src
    #             language: system
    #             pass_filenames: false

    # -   repo: local
    #     hooks:
    #         -   id: tests
    #             name: Tests
    #             entry: pytest
    #             language: system
    #             stages: [push]
    #             pass_filenames: false

    -   repo: https://github.com/NASA-AMMOS/slim-detect-secrets
        # using commit id for now, will change to tag when official version is released
        rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
        hooks:
          - id: detect-secrets
            args:
              - '--baseline'
              - '.secrets.baseline'
              - --exclude-files '\.secrets..*'
              - --exclude-files '\.git.*'
              - --exclude-files '\.pre-commit-config\.yaml'
              - --exclude-files '\.mypy_cache'
              - --exclude-files '\.pytest_cache'
              - --exclude-files '\.tox'
              - --exclude-files '\.venv'
              - --exclude-files 'venv'
              - --exclude-files 'dist'
              - --exclude-files 'build'
              - --exclude-files '.*\.egg-info'
